# Generated by Django 5.2.6 on 2025-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('normal', 'normal'), ('urgent', 'urgent'), ('critical', 'critical')], default='normal', max_length=65),
        ),
    ]
