# Generated by Django 5.2.6 on 2025-09-27 14:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('os_type', models.CharField(blank=True, max_length=20)),
                ('browser_type', models.CharField(blank=True, max_length=20)),
                ('download_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('expired', 'Link Expired'), ('invalid', 'Invalid Token')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Log',
                'verbose_name_plural': 'Download Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_do_user_id_b97852_idx'), models.Index(fields=['order_item', 'created_at'], name='accounts_do_order_i_9e5997_idx'), models.Index(fields=['download_status'], name='accounts_do_downloa_b5333d_idx')],
            },
        ),
    ]
