# Generated by Django 5.2.6 on 2025-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_downloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='download_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='browser_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='download_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('expired', 'Link Expired'), ('invalid', 'Invalid Token'), ('limit_exceeded', 'Download Limit Exceeded')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='os_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
