# Generated by Django 5.2.6 on 2025-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_downloadlog_download_duration_downloadlog_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlog',
            name='browser_type',
        ),
        migrations.RemoveField(
            model_name='downloadlog',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='downloadlog',
            name='os_type',
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='browser_family',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='browser_version',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='device_brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='device_family',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='device_model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='is_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='os_family',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='os_version',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
